### ISSUE TITLE
_MeCab has no attribute 'delete_Path'

### ISSUE THREAD

**Issue by calubgld** [ikegami-yukino/mecab#16]
Hi,

Seeking your support. I can't seem to use MeCab. Below are the details and error message. Please advice for possible fix.

Windows10
Python3.10
MeCab 0.996.3

C:\Users\rfs20\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/rfs20/PycharmProjects/pythonProject/main.py
Traceback (most recent call last):
  File "C:\Users\rfs20\PycharmProjects\pythonProject\main.py", line 1, in <module>
    import MeCab
  File "C:\Users\rfs20\AppData\Local\Programs\Python\Python310\lib\site-packages\MeCab.py", line 83, in <module>
    class Path(object):
  File "C:\Users\rfs20\AppData\Local\Programs\Python\Python310\lib\site-packages\MeCab.py", line 95, in Path
    __swig_destroy__ = _MeCab.delete_Path
AttributeError: module '_MeCab' has no attribute 'delete_Path'

Process finished with exit code 1

**Comment by ikegami-yukino** [comment]
@calubgld 
I uploaded wheels for Python 3.10.
Please run the following command:
```
pip uninstall mecab
pip install mecab
```
